# Generated by Django 5.2.1 on 2025-05-27 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billsplit',
            unique_together={('bill', 'user')},
        ),
    ]
